# Generated by Django 5.2.3 on 2025-07-15 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("plea_of_guilty", "Plea of Guilty"),
                            ("bail_application", "Bail Application"),
                        ],
                        default="plea_of_guilty",
                        help_text="The type of document template to use for this form",
                        max_length=50,
                    ),
                ),
                (
                    "template_config",
                    models.JSONField(
                        blank=True,
                        help_text="Configuration for document generation, including sections to include, their order, and formatting.",
                        null=True,
                    ),
                ),
                (
                    "sections",
                    models.JSONField(
                        blank=True,
                        help_text="List of sections for this form, as an array of objects with id and name.",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=1024)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("MC", "Multiple Choice"),
                            ("CHECK", "Checkboxes"),
                            ("DROP", "Dropdown"),
                            ("DATE", "Date"),
                        ],
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "output_template",
                    models.TextField(
                        blank=True,
                        help_text="Sample submission text. Use {{answer}} to insert the user's answer.",
                    ),
                ),
                ("hidden", models.BooleanField(default=False)),
                (
                    "section_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Section ID this question belongs to (from form.sections array, not a FK)",
                        null=True,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="forms.form",
                    ),
                ),
                (
                    "triggers_question",
                    models.ManyToManyField(
                        blank=True,
                        help_text="If this question is answered, these questions will be shown.",
                        related_name="triggered_by_question",
                        to="forms.question",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="forms.question",
                    ),
                ),
                (
                    "triggers_question",
                    models.ManyToManyField(
                        blank=True,
                        help_text="If this option is selected, these questions will be shown.",
                        related_name="triggered_by_options",
                        to="forms.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_honorific", models.CharField(blank=True, max_length=10)),
                ("client_first_name", models.CharField(max_length=255)),
                ("client_surname", models.CharField(max_length=255)),
                ("submission_date", models.DateField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="forms.form"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField()),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="forms.question",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="forms.submission",
                    ),
                ),
            ],
        ),
    ]
