# Generated by Django 5.2.3 on 2025-06-30 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=1024)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("PARAGRAPH", "Paragraph"),
                            ("MC", "Multiple Choice"),
                            ("CHECK", "Checkboxes"),
                            ("DROP", "Dropdown"),
                        ],
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "output_template",
                    models.TextField(
                        blank=True,
                        help_text="Sample submission text. Use {{answer}} to insert the user's answer.",
                    ),
                ),
                ("hidden", models.BooleanField(default=False)),
                (
                    "any_option_triggers_question",
                    models.ForeignKey(
                        blank=True,
                        help_text="If any option is selected, this question will be shown (for dropdowns).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_by_any_option",
                        to="forms.question",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="forms.form",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="forms.question",
                    ),
                ),
                (
                    "triggers_question",
                    models.ForeignKey(
                        blank=True,
                        help_text="If this option is selected, this question will be shown.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_by_options",
                        to="forms.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="forms.form"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="forms.question"
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="forms.submission",
                    ),
                ),
            ],
        ),
    ]
