# Generated by Django 5.2.3 on 2025-07-01 01:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="client_name",
            field=models.CharField(default="sean", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="submission",
            name="submission_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "Text"),
                    ("MC", "Multiple Choice"),
                    ("CHECK", "Checkboxes"),
                    ("DROP", "Dropdown"),
                ],
                max_length=10,
            ),
        ),
    ]
