# Generated by Django 5.2.3 on 2025-07-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0002_submission_client_name_submission_submission_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="section_id",
            field=models.IntegerField(
                blank=True,
                help_text="Section ID this question belongs to (from form.sections array, not a FK)",
                null=True,
            ),
        ),
    ]
