# Generated by Django 5.2.3 on 2025-07-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0003_question_section_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="sections",
            field=models.JSONField(
                blank=True,
                help_text="List of sections for this form, as an array of objects with id and name.",
                null=True,
            ),
        ),
    ]
