# Generated by Django 5.2.3 on 2025-07-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0004_form_sections"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="option",
            name="triggers_question",
        ),
        migrations.AddField(
            model_name="option",
            name="triggers_question",
            field=models.ManyToManyField(
                blank=True,
                help_text="If this option is selected, these questions will be shown.",
                related_name="triggered_by_options",
                to="forms.question",
            ),
        ),
    ]
