# Generated by Django 5.2.3 on 2025-07-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0006_alter_answer_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "Text"),
                    ("MC", "Multiple Choice"),
                    ("CHECK", "Checkboxes"),
                    ("DROP", "Dropdown"),
                    ("DATE", "Date"),
                ],
                max_length=10,
            ),
        ),
    ]
