# Generated by Django 5.2.3 on 2025-07-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0007_alter_question_question_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="any_option_triggers_question",
        ),
    ]
