# Generated by Django 5.2.3 on 2025-07-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0007_alter_question_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="triggers_question",
            field=models.ManyToManyField(
                blank=True,
                help_text="If this question is answered, these questions will be shown.",
                related_name="triggered_by_question",
                to="forms.question",
            ),
        ),
    ]
